UBUNTU: build/config: Disable apm_emu, pasemi_mac and cbe_cpufreq on ppc64
These did not compile. Missing symbols:

ERROR: "irq_map" [drivers/net/pasemi_mac.ko] undefined!
ERROR: "pmu_batteries" [drivers/macintosh/apm_emu.ko] undefined!
ERROR: "pmu_battery_count" [drivers/macintosh/apm_emu.ko] undefined!
ERROR: "pmu_power_flags" [drivers/macintosh/apm_emu.ko] undefined!
ERROR: ".cpufreq_set_policy" [arch/powerpc/platforms/cell/cbe_cpufreq.ko] undefined!

Signed-off-by: Ben Collins <bcollins@ubuntu.com>