UBUNTU: PM: Introduce PM_EVENT_HIBERNATE callback state Bug: #201086
commit 3a2d5b700132f35401f1d9e22fe3c2cab02c2549
Author: Rafael J. Wysocki <rjw@sisk.pl>
Date:   Sat Feb 23 19:13:25 2008 +0100

    PM: Introduce PM_EVENT_HIBERNATE callback state

    During the last step of hibernation in the "platform" mode (with the
    help of ACPI) we use the suspend code, including the devices'
    ->suspend() methods, to prepare the system for entering the ACPI S4
    system sleep state.

    But at least for some devices the operations performed by the
    ->suspend() callback in that case must be different from its operations
    during regular suspend.

    For this reason, introduce the new PM event type PM_EVENT_HIBERNATE and
    pass it to the device drivers' ->suspend() methods during the last phase
    of hibernation, so that they can distinguish this case and handle it as
    appropriate.  Modify the drivers that handle PM_EVENT_SUSPEND in a
    special way and need to handle PM_EVENT_HIBERNATE in the same way.

    These changes are necessary to fix a hibernation regression related
    to the i915 driver (ref. http://lkml.org/lkml/2008/2/22/488).

    Signed-off-by: Rafael J. Wysocki <rjw@sisk.pl>
    Acked-by: Pavel Machek <pavel@ucw.cz>
    Tested-by: Jeff Chua <jeff.chua.linux@gmail.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit 038eb0ea04b245351be34b0ae76b55eee4603989
Author: Mirco Tischler <mt-ml@gmx.de>
Date:   Sun Feb 24 05:16:39 2008 +0100

    Fix u132-hcd.c compile error

    This fixes the following compile error caused by commit
    3a2d5b700132f35401f1d9e22fe3c2cab02c2549 ("PM: Introduce
    PM_EVENT_HIBERNATE callback state")

        CC [M]  drivers/usb/host/u132-hcd.o
      drivers/usb/host/u132-hcd.c: In function ‘u132_suspend’:
      drivers/usb/host/u132-hcd.c:3224: error: expected expression before ‘int’
      drivers/usb/host/u132-hcd.c:3225: error: ‘ports’ undeclared (first use in
      ...

    Signed-off-by: Mirco Tischler <mt-ml@gmx.de>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Stefan Bader <stefan.bader@canonical.com>